action: download
coords-dir: examples/geojsons            
start: 2022-12-01T00:00:00     
end: 2022-12-31T23:00:00       
preds: [TA, PA, P, WS, WD, VPD, RH, CO2] 
aggregation-type: MONTHLY      
id-field: GID                  