# download_config.yaml
action: download
coords-dir: geojsons            # directory of JSON files | nothing
start: 2024-12-01T00:00:00      # format: YYYY-MM-DDTHH:MM:SS
end: 2024-12-31T23:00:00        # format: YYYY-MM-DDTHH:MM:SS
preds: [TA, PA, P, WS, WD, USTAR, NETRAD, SW_IN, SW_IN_POT, SW_OUT, LW_IN, LW_OUT, LE, G, H, VPD, RH, CO2] # AmeriFlux predictors | nothing
aggregation-type: MONTHLY       # DAILY | MONTHLY | nothing
id-field:                    # Identifier field | nothing