name: carbon2
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.3.3
  - pandas=2.3.3
  - xarray
  - netcdf4
  - eccodes
  - rioxarray
  - dask
  - numexpr
  - pyyaml
  - beautifulsoup4
  - pip
  - pip:
      - -e . 
